// Every piece of text the browser shows to the person using it lives here.
// Command-line flags, logs and output meant for agents stay in English and are not listed.
export const STRINGS = {
  menu: {
    copy: "复制",
    openLinkInNewTab: "在新标签页打开链接",
    copyLinkAddress: "复制链接地址",
    sendToAgent: "发送给 agent",
    stopSelection: "停止选取",
    record: "录制",
    completeRecording: "完成录制",
    inspect: "检查",
    closePane: "关闭窗格",
  },
  palette: {
    findInPage: "在页面中查找",
    recordPage: "录制页面",
    stopRecording: "停止录制",
    completeRecording: "完成录制",
    sendToAgent: "发送给 agent",
    stopSelection: "停止选取",
    openDevtools: "打开开发者工具",
    closeDevtools: "关闭开发者工具",
    dockDevtoolsRight: "开发者工具停靠在右侧",
    dockDevtoolsBottom: "开发者工具停靠在底部",
    openApp: (name: string) => `打开 ${name}`,
    noMatches: "没有匹配的操作",
  },
  tabs: {
    newTab: "新标签页",
  },
  download: {
    saved: "已保存",
    failed: "下载失败",
    downloading: "正在下载",
  },
  toast: {
    copied: "已复制到剪贴板",
    sentToAgent: "已发送给 agent",
    quitHint: "按 ctrl+q 退出",
    couldNotLaunch: (name: string) => `无法启动 ${name}`,
    recordingCapped: (minutes: number) => `录制已达到 ${minutes} 分钟上限`,
    nothingCaptured: "没有录到任何画面",
    captureFailed: (message: string) => `画面捕获失败：${message}`,
    recordingFailed: (message: string) => `录制失败：${message}`,
  },
  pane: {
    unknownPane: "无法确定浏览器所在的窗格",
    noShell: (id: string) => `herdr 没有返回窗格 ${id} 的 shell 进程`,
    notOwnPane: (id: string) => `窗格 ${id} 不是浏览器所在的窗格，未关闭`,
  },
  record: {
    click: "点击",
    linkOpened: "打开了链接",
    reload: "重新加载",
    pageLoad: "页面加载",
    hasEdits: "有标注",
    framesDropped: (count: number) => `丢失 ${count} 帧`,
    tabToCycle: "按 tab 切换",
    tabToView: "按 tab 查看",
    complete: "完成",
    stop: "停止",
    screenshot: "截图",
    cropFrame: "裁剪当前帧",
    cropVideo: "裁剪整段视频",
  },
};
